### ISSUE TITLE
Various error messages

### ISSUE THREAD

**Issue by ghost** [lformella/xdcc-grabscher#27]
I do not know how to categorize the following messages but I want to make you aware of it.
If I can provide further information please let me know.

31.12.2013 08:36:00 [Info] Failed to send. Disconnecting. System.AggregateException: One or more errors occured ---> System.ObjectDisposedException: The object was used after being disposed.
  at System.Net.Sockets.NetworkStream.CheckDisposed () [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult ar) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory+<FromAsync>c__AnonStorey1B.<>m__12 (IAsyncResult l) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Object].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
 --> (Inner exception 0) System.ObjectDisposedException: The object was used after being disposed.
  at System.Net.Sockets.NetworkStream.CheckDisposed () [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult ar) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory+<FromAsync>c__AnonStorey1B.<>m__12 (IAsyncResult l) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Object].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0

31.12.2013 08:35:59 [Info] Failed to send. Disconnecting. System.AggregateException: One or more errors occured ---> System.ObjectDisposedException: The object was used after being disposed.
  at System.Net.Sockets.NetworkStream.CheckDisposed () [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult ar) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory+<FromAsync>c__AnonStorey1B.<>m__12 (IAsyncResult l) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Object].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
 --> (Inner exception 0) System.ObjectDisposedException: The object was used after being disposed.
  at System.Net.Sockets.NetworkStream.CheckDisposed () [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult ar) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory+<FromAsync>c__AnonStorey1B.<>m__12 (IAsyncResult l) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Object].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0

31.12.2013 08:35:59 [Info] Failed to send. Disconnecting. System.AggregateException: One or more errors occured ---> System.ObjectDisposedException: The object was used after being disposed.
  at System.Net.Sockets.NetworkStream.CheckDisposed () [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult ar) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory+<FromAsync>c__AnonStorey1B.<>m__12 (IAsyncResult l) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Object].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
 --> (Inner exception 0) System.ObjectDisposedException: The object was used after being disposed.
  at System.Net.Sockets.NetworkStream.CheckDisposed () [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult ar) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory+<FromAsync>c__AnonStorey1B.<>m__12 (IAsyncResult l) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Object].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0

**Comment by ghost** [comment]
Yet another one:

31-12-2013 17:27:29,669 FATAL [85] 0:XG.Server.Plugin.Core.Irc.Download(94.23.228.84:35053).StartRun()
System.IO.IOException: Read failure ---> System.Net.Sockets.SocketException: interrupted
  at System.Net.Sockets.Socket.Receive (System.Byte[] buffer, Int32 offset, Int32 size, SocketFlags flags) [0x00000] in <filename unknown>:0
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0
  at System.IO.BinaryReader.ReadBytes (Int32 count) [0x00000] in <filename unknown>:0
  at XG.Server.Plugin.Core.Irc.Download.StartRun () [0x00000] in <filename unknown>:0

**Comment by ghost** [comment]
01-01-2014 11:40:26,097 FATAL [Threadpool worker] 0:XG.Server.Plugin.General.Webserver.Websocket.Server.OnSearchExternal(Riley Reid) cant load external search
System.Net.WebException: Error getting response stream (ReadDone2): ReceiveFailure ---> System.Exception:    at System.Net.WebConnection.HandleError(WebExceptionStatus st, System.Exception e, System.String where)
   at System.Net.WebConnection.ReadDone(IAsyncResult result)
  at System.Net.WebConnection.HandleError (WebExceptionStatus st, System.Exception e, System.String where) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0
  at XG.Server.Plugin.General.Webserver.Websocket.Server.SearchExternal (System.String search) [0x00000] in <filename unknown>:0

**Comment by lformella** [comment]
I changed the exception handling in XG 3.0.0.0 (https://github.com/lformella/xdcc-grabscher/releases/tag/v3.0.0.0) there should be less exceptions printed.

Normally the exceptions will be echoed, but you can ignore them unless XG crashes or a feature does not work as expected. Except for downloads / server connections because the bots / servers might be dropping connections which will lead in exceptions.

The website xg.bitpir.at is down atm, so you cant use the external search.
