### ISSUE TITLE
Exception while building latest master

### ISSUE THREAD

**Issue by Khundian** [lformella/xdcc-grabscher#56]
System.MissingMemberException was unhandled
  _HResult=-2146233070
  _message=The server factory could not be located for the given input: Nowin
  HResult=-2146233070
  IsTransient=false
  Message=The server factory could not be located for the given input: Nowin
  Source=Microsoft.Owin.Hosting
  StackTrace:
       at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveServerFactory(StartContext context)
       at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
       at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
       at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
       at XG.Plugin.Webserver.Plugin.StartRun() in c:\Users\Len\Desktop\xdcc-grabscher-master\XG.Plugin.Webserver\Plugin.cs:line 93
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Visual studio linked this page as troubleshooting tip: http://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k%28EHMissingMember%29;k%28TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5%29;k%28DevLang-csharp%29&rd=true

**Comment by lformella** [comment]
Take a look here: https://github.com/lformella/xdcc-grabscher/wiki/troubleshooting#startup-errors

Sometimes Visual Studio forgets to copy some needed libraries into the bin folder. I dont know if they are not correctly embedded / linked / whatever into the visual project files.

**Comment by Khundian** [comment]
thanks for the info, its working now :)
