### ISSUE TITLE
Missing "/favicon.ico", "/image&ODay", "/image&Ok"

### ISSUE THREAD

**Issue by Strubbl** [lformella/xdcc-grabscher#7]
my XG server (installed from XG_Server_0.9.1.msi) spams me in the console on Win7 64bit when clicking around in the web interface:

```
10-10-2012 10:11:54,144 FATAL [27] OpenClient(/favicon.ico) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
10-10-2012 10:11:54,510 FATAL [30] OpenClient(/favicon.ico) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
10-10-2012 10:11:54,515 FATAL [31] OpenClient(/favicon.ico) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
10-10-2012 10:12:49,260 FATAL [37] OpenClient(/image&ODay) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
10-10-2012 10:12:49,261 FATAL [38] OpenClient(/image&OWeek) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
10-10-2012 10:12:49,264 FATAL [40] OpenClient(/image&Ok) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
10-10-2012 10:12:49,264 FATAL [39] OpenClient(/image&Packet) (Plugin:0)
System.TypeInitializationException: The type initializer for 'Nested' threw an exception. ---> Syste
m.NullReferenceException: Object reference not set to an instance of an object.
   at XG.Client.Web.ImageLoaderWeb.LoadImage(Stream aStream)
   at XG.Client.Web.ImageLoaderWeb..ctor()
   at XG.Client.Web.ImageLoaderWeb.Nested..cctor()
   --- End of inner exception stack trace ---
   at XG.Client.Web.ImageLoaderWeb.get_Instance()
   at XG.Server.Plugin.General.Webserver.Plugin.OpenClient(Object aObject)
```

Is it missing a favicon.ico? And can you explain the same message for the "/image&ODay", "/image&Ok" and so on?

**Comment by lformella** [comment]
I removed most of the icons and use an icon font instead. So the server tries to load images which are not in the dll anymore. Does this error still occur in the current version?

**Comment by Strubbl** [comment]
Don't have the build tools to compile latest version of XG in Wintendo. Plus, I don't have it installed anymore. If there will be a XG_Server_0.9.2.msi (or newer), I can install and test it again.
