### ISSUE TITLE
Unhandled Exception Elasticsearch

### ISSUE THREAD

**Issue by Khundian** [lformella/xdcc-grabscher#75]
First and foremost, many thanks for keeping on the task of developing and supporting this application.

When trying to run the latest version of xdcc grabber with elasticsearch, I get this unhandled exception:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Elasticsearch.net, Version=1.0.0.0 Culture=neutral, PublicKeyToken=96c599bbe3e70f5d' or one of its dependencies. The system cannot find the file specified.

at XG.Plugin.ElasticSearch.Plugin.StartRun()
at System.Threading.ThreadHelper.ThreadStart_Context(Object_state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

Any advice would be appreciated :)

**Comment by lformella** [comment]
Are you using Windows? On OSX the mono build is working.
