### ISSUE TITLE
Unable to get packets FATAL error

### ISSUE THREAD

**Issue by little0831** [lformella/xdcc-grabscher#84]
Output when a packet fails:

C:\Program Files (x86)\XG>xg.application.exe
11-01-2015 11:10:11,972 FATAL [91.121.23.104:57865] 165:XG.Plugin.Irc.BotDownloa
d.StartRun()
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a
 socket in a way forbidden by its access permissions 91.121.23.104:57865
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at XG.Plugin.Irc.BotDownload.StartRun() in c:\Users\Lars\Documents\GitHub\xdc
c-grabscher\XG.Plugin.Irc\BotDownload.cs:line 118

Not sure if this is a GP or Firewall issue.... also, I have no users named Lars on my box.
Windows Server 2008 R2 SP1, .net 4.5.2

Anything else that might be needed please let me know.

**Comment by little0831** [comment]
Additional outputs:

11-01-2015 11:19:38,387 FATAL [95.211.130.71:43929] 165:XG.Plugin.Irc.BotDownloa
d.StartRun()
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a
 socket in a way forbidden by its access permissions 95.211.130.71:43929
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at XG.Plugin.Irc.BotDownload.StartRun() in c:\Users\Lars\Documents\GitHub\xdc
c-grabscher\XG.Plugin.Irc\BotDownload.cs:line 118
11-01-2015 11:19:45,338 FATAL [216.250.115.17:59640] 165:XG.Plugin.Irc.BotDownlo
ad.StartRun()
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a
 socket in a way forbidden by its access permissions 216.250.115.17:59640
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at XG.Plugin.Irc.BotDownload.StartRun() in c:\Users\Lars\Documents\GitHub\xdc
c-grabscher\XG.Plugin.Irc\BotDownload.cs:line 118
11-01-2015 11:20:47,728 FATAL [46.105.124.98:40764] 165:XG.Plugin.Irc.BotDownloa
d.StartRun()
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a
 socket in a way forbidden by its access permissions 46.105.124.98:40764
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at XG.Plugin.Irc.BotDownload.StartRun() in c:\Users\Lars\Documents\GitHub\xdc
c-grabscher\XG.Plugin.Irc\BotDownload.cs:line 118

As another note, I have not successfully grabbed a couple packs. If I use another client though (i.e. mIRC) the packets are downloaded just fine, seems to be an issue with xdcc-grabscher.

Thank you!

**Comment by little0831** [comment]
Figured it out! Looks like PeerBlock was blacklisting some IP addresses for bots. When I unblock the IP then it works. Reason the other client was working was because it was outside of the VM for Windows.

Sorry to report a false issue but hopefully this helps anyone who might also be having issues.

----- Still interesting that it would show "\users\lars" considering I don't have a user by that name nor do I have a folder structure matching that. -----

Thank you!

**Comment by lformella** [comment]
The XG windows version was compiled in this folder structure. Apparently Visual Studio is adding some debug informations including the path to the source file to the build.
